export const CREATE_NOTE = "CREATE_NOTE";
export const RETRIEVE_NOTES = "RETRIEVE_NOTES";
export const UPDATE_NOTE = "UPDATE_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
export const DELETE_ALL_NOTES = "DELETE_ALL_NOTES";